<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageID>GamebookGenerator.Core</PackageID>
    <OutputType>Library</OutputType>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Ast.fs" />
    <Compile Include="Helpers.fs" />
    <Compile Include="Parser/Common.fs" />
    <Compile Include="Parser/Inline.fs" />
    <Compile Include="Parser/Line.fs" />
  </ItemGroup>
  <Import Project="..\..\.paket\Paket.Restore.targets" />
</Project>
